/bngtech_sensor_bridge:
  ros__parameters:
    settings:
      ip: 10.5.5.10
      port: 64256
      launch: False
      level: smallgrid
      vehicle:
        model: etk800
        position: [0.0, 0.0, 0.0]
        orientation: [0.0, 0.0, 0.0, 1.0]
      ai_span: false
      # deterministic_hz: 200
    
    bag_writer:
      path: "output.bag"

    # classic_sensors: [ 'timer', 'state', 'electrics' ]
    classic_sensors: []

    transformers:
      _0:
        type: copy
        source: imu
        destination: imu_track 

      _1:
        type: map_to_track
        pose_source: imu
        tf_destination: track_tf
        apply_to: [
          "position: imu_track[].position",
          "orientation: imu_track[].orientation",
          "vector: imu_track[].angular_velocity",
        ]
      

    automated_sensors:
      _0:
        name: imu
        type: imu
        is_using_gravity: false
        pos: [0.0, 0.0, 1.7]
        dir: [0.0, -1.0, 0.0]
        up: [1.0, 0.0, 0.0]
        physics_update_time: 0.003
        # accel_frequency_cutoff:
        # gyro_frequency_cutoff:
        # gyro_window_width:
        # accel_window_width:

      _1:
        name: gps
        type: gps
        physics_update_time: 0.01
        pos: [0.0, 0.0, 1.7]
        ref_lat: 44.6398464
        ref_lon: 10.9314048

    outputs:
      _0:
        type: pose
        source: imu
        topic: /pose_gt
        frame_id: map
        covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
      
      _1:
        type: imu
        source: imu
        topic: /imu/data
        frame_id: imu_link
        orientation_covariance: [0.1, 0.0, 0.0,
                                0.0, 0.1, 0.0,
                                0.0, 0.0, 0.1]
        angular_velocity_covariance: [0.1, 0.0, 0.0,
                                      0.0, 0.1, 0.0,
                                      0.0, 0.0, 0.1]
        linear_acceleration_covariance: [0.1, 0.0, 0.0,
                                        0.0, 0.1, 0.0,
                                        0.0, 0.0, 0.1]

      _2:
        type: gps
        source: gps
        topic: /gps/fix
        frame_id: imu_link
        position_covariance: [0.1, 0.0, 0.0,
                              0.0, 0.1, 0.0,
                              0.0, 0.0, 0.1]

      _3:
        type: tf
        source: track_tf
        topic: /tf_static
        qos: transient_local
        frame_id: map
        child_frame_id: track

      _4:
        type: imu
        source: imu
        topic: /imu/world_data
        frame_id: imu_link
        orientation_covariance: [0.1, 0.0, 0.0,
                                0.0, 0.1, 0.0,
                                0.0, 0.0, 0.1]
        angular_velocity_covariance: [0.1, 0.0, 0.0,
                                      0.0, 0.1, 0.0,
                                      0.0, 0.0, 0.1]
        linear_acceleration_covariance: [0.1, 0.0, 0.0,
                                        0.0, 0.1, 0.0,
                                        0.0, 0.0, 0.1]

      # _4:
        #  type: tf
        #  source: imu
        #  topic: /tf
        #  frame_id: track
        #  child_frame_id: imu_link
