/bngtech_sensor_bridge:
  ros__parameters:
    settings:
      ip: 192.168.1.2
      port: 64256
      launch: False
      level: smallgrid
      vehicle:
        model: etk800
        position: [0.0, 0.0, 0.0]
        orientation: [0.0, 0.0, 0.0, 1.0]
      ai_span: false
      deterministic_hz: -1.0

    classic_sensors: [ 'timer', 'state', 'electrics' ]

    transformers:
      _0:
        type: map_to_track
        pose_source: state
        apply_to: [
          "position: state[].position",
          "orientation: state[].orientation",
          "vector: state[].velocity",
          "position: imu[].position",
          "orientation: imu[].orientation",
        ]
      

    automated_sensors:
      _0:
        name: imu
        type: imu
        is_using_gravity: false
        pos: [0.0, 0.0, 1.7]
        dir: [0.0, -1.0, 0.0]
        up: [1.0, 0.0, 0.0]
        physics_update_time: 0.003
        # accel_frequency_cutoff: 
        # gyro_frequency_cutoff:
        # gyro_window_width: 
        # accel_window_width: 

      _1:
        name: gps
        type: gps
        physics_update_time: 0.01
        pos: [0.0, 0.0, 1.7]
        ref_lat: 0.0
        ref_lon: 0.0

    outputs:
      _0:
        type: pose
        source: state
        topic: /bng/pose
        frame_id: track
        covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
      
      _1:
        type: tf
        source: state
        topic: /tf
        frame_id: track
        child_frame_id: imu_link

      _2:
        type: wheelspeed
        source: electrics
        topic: /bng/wheelspeed
        frame_id: imu_link
        variance: 0.1
      
      _3:
        type: imu
        source: imu
        topic: /bng/imu/data
        frame_id: imu_link
        orientation_covariance: [0.1, 0.0, 0.0,
                                0.0, 0.1, 0.0,
                                0.0, 0.0, 0.1]
        angular_velocity_covariance: [0.1, 0.0, 0.0,
                                      0.0, 0.1, 0.0,
                                      0.0, 0.0, 0.1]
        linear_acceleration_covariance: [0.1, 0.0, 0.0,
                                        0.0, 0.1, 0.0,
                                        0.0, 0.0, 0.1]

      _4:
        type: pose
        source: imu
        topic: /bng/imu/pose
        frame_id: track
        covariance: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                     0.0, 1.0, 0.0, 0.0, 0.0, 0.0,
                     0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
                     0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
                     0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                     0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

      _5:
        type: gps
        source: gps
        topic: /bng/gps
        frame_id: map
        position_covariance: [0.1, 0.0, 0.0,
                              0.0, 0.1, 0.0,
                              0.0, 0.0, 0.1]